#!/bin/bash

# Define the key name
key_name="school"

# Define the number of bits
key_bits=4096

# Define the passphrase
passphrase="betty"

# Generate the key pair
ssh-keygen -t rsa -b "$key_bits" -N "$passphrase" -f "$key_name"

# Display the key information
echo "Key pair generated successfully."
ls -l "$key_name" "$key_name.pub"
